import { hashPassword, hashSecret } from "./crypto";
import type { Observation, StoreShape, Trace } from "./types";

const PROJECT = "prj-vet-demo";
const ORG = "org_demo";

function at(iso: string) {
  return iso;
}

function obs(partial: Partial<Observation> & Pick<Observation, "id" | "traceId" | "type" | "name" | "startTime">): Observation {
  return {
    projectId: PROJECT,
    parentId: null,
    usage: null,
    model: null,
    provider: null,
    region: null,
    metadata: {},
    status: "ok",
    input: null,
    output: null,
    endTime: null,
    ...partial,
  };
}

export const DEMO_KEYS = {
  publicKey: "pk-vet-demo",
  secretKey: "sk-vet-demo",
  langfusePublicKey: "pk-lf-vet-demo",
  langfuseSecretKey: "sk-lf-vet-demo",
  email: "demo@vet.dev",
  password: "demodemo",
  consolePassword: "demodemo",
  zaloAppId: "1234567890",
  zaloOaSecret: "demo-oa-secret",
  zaloBotToken: "demo-bot-token",
  larkToken: "demo-lark-token",
  gchatToken: "demo-gchat-token",
  fptToken: "demo-fpt-token",
};

export function seedStore(): StoreShape {
  const t1 = "2026-09-09T14:02:01.000Z";
  const traces: Trace[] = [
    {
      id: "tr_zalo_huy_don",
      projectId: PROJECT,
      name: "zalo-oa · hủy đơn",
      sessionId: "zalo_oa:user_847712",
      userId: "user_847712",
      channel: "zalo_oa",
      routeId: "rt_zalo_fpt_claude",
      release: "oa-prod",
      environment: "production",
      tags: ["zalo", "cx"],
      startTime: t1,
      endTime: "2026-09-09T14:03:08.000Z",
      status: "ok",
      metadata: { oa_id: "oa_9901" },
    },
    {
      id: "tr_zalo_chao",
      projectId: PROJECT,
      name: "zalo-oa · follow + chào",
      sessionId: "zalo_oa:user_229001",
      userId: "user_229001",
      channel: "zalo_oa",
      routeId: "rt_zalo_fpt_claude",
      release: "oa-prod",
      environment: "production",
      tags: ["zalo"],
      startTime: "2026-09-09T09:11:00.000Z",
      endTime: "2026-09-09T09:11:22.000Z",
      status: "ok",
      metadata: {},
    },
    {
      id: "tr_crm_tool",
      projectId: PROJECT,
      name: "zalo-oa · tra cứu đơn",
      sessionId: "zalo_oa:user_847712",
      userId: "user_847712",
      channel: "zalo_oa",
      routeId: "rt_zalo_fpt_claude",
      release: "oa-prod",
      environment: "production",
      tags: ["zalo", "tool"],
      startTime: "2026-09-09T14:04:00.000Z",
      endTime: "2026-09-09T14:04:41.000Z",
      status: "ok",
      metadata: {},
    },
    {
      id: "tr_viettel_tts",
      projectId: PROJECT,
      name: "zalo-oa · TTS Viettel",
      sessionId: "zalo_oa:user_551002",
      userId: "user_551002",
      channel: "zalo_oa",
      routeId: "rt_voice",
      release: "oa-prod",
      environment: "production",
      tags: ["viettel", "speech"],
      startTime: "2026-09-09T11:20:00.000Z",
      endTime: "2026-09-09T11:20:18.000Z",
      status: "ok",
      metadata: {},
    },
    {
      id: "tr_anthropic_err",
      projectId: PROJECT,
      name: "generation · Anthropic 429",
      sessionId: "zalo_oa:user_847712",
      userId: "user_847712",
      channel: "zalo_oa",
      routeId: "rt_zalo_fpt_claude",
      release: "oa-prod",
      environment: "production",
      tags: ["anthropic", "error"],
      startTime: "2026-09-08T18:44:00.000Z",
      endTime: "2026-09-08T18:44:02.000Z",
      status: "error",
      metadata: { http: 429 },
    },
    {
      id: "tr_lark_dm",
      projectId: PROJECT,
      name: "lark · DM nội bộ",
      sessionId: "lark:ou_88aa",
      userId: "ou_88aa",
      channel: "lark",
      routeId: "rt_lark",
      release: "lark-prod",
      environment: "production",
      tags: ["lark"],
      startTime: "2026-09-09T08:02:10.000Z",
      endTime: "2026-09-09T08:02:40.000Z",
      status: "ok",
      metadata: {},
    },
    {
      id: "tr_gchat",
      projectId: PROJECT,
      name: "google-chat · space hỗ trợ",
      sessionId: "gchat:spaces_abc:users_1",
      userId: "users/113",
      channel: "gchat",
      routeId: "rt_gchat",
      release: "gchat-prod",
      environment: "production",
      tags: ["gchat"],
      startTime: "2026-09-09T07:30:00.000Z",
      endTime: "2026-09-09T07:30:19.000Z",
      status: "ok",
      metadata: { space: "spaces/abc" },
    },
    {
      id: "tr_playground",
      projectId: PROJECT,
      name: "playground · soạn prompt CX",
      sessionId: null,
      userId: "demo@vet.dev",
      channel: null,
      routeId: null,
      release: "dev",
      environment: "default",
      tags: ["playground"],
      startTime: "2026-09-09T16:01:00.000Z",
      endTime: "2026-09-09T16:01:04.000Z",
      status: "ok",
      metadata: {},
    },
    {
      id: "tr_bedrock",
      projectId: PROJECT,
      name: "generation · Bedrock Nova",
      sessionId: "zalo_oa:user_3301",
      userId: "user_3301",
      channel: "zalo_oa",
      routeId: "rt_zalo_bedrock",
      release: "oa-prod",
      environment: "production",
      tags: ["bedrock"],
      startTime: "2026-09-09T12:10:00.000Z",
      endTime: "2026-09-09T12:10:09.000Z",
      status: "ok",
      metadata: { region: "ap-southeast-1" },
    },
    {
      id: "tr_vertex",
      projectId: PROJECT,
      name: "generation · Vertex Gemini",
      sessionId: null,
      userId: null,
      channel: null,
      routeId: null,
      release: "dev",
      environment: "staging",
      tags: ["vertex"],
      startTime: "2026-09-09T12:12:00.000Z",
      endTime: "2026-09-09T12:12:06.000Z",
      status: "ok",
      metadata: { location: "asia-southeast1" },
    },
    {
      id: "tr_foundry_teams",
      projectId: PROJECT,
      name: "msteams · Foundry trong turn",
      sessionId: "msteams:29:conv",
      userId: "29:aad-user",
      channel: "msteams",
      routeId: "rt_teams_foundry",
      release: "bot-dotnet-2.4",
      environment: "production",
      tags: ["foundry", "dotnet"],
      startTime: "2026-09-09T10:00:00.000Z",
      endTime: "2026-09-09T10:00:14.000Z",
      status: "ok",
      metadata: { deployment: "gpt-4o-cx" },
    },
    {
      id: "tr_fpt_webhook",
      projectId: PROJECT,
      name: "fpt-conversation · webhook trả lời",
      sessionId: "zalo_oa:user_9102",
      userId: "user_9102",
      channel: "zalo_oa",
      routeId: "rt_zalo_fpt_claude",
      release: "oa-prod",
      environment: "production",
      tags: ["fpt"],
      startTime: "2026-09-09T13:40:00.000Z",
      endTime: "2026-09-09T13:40:08.000Z",
      status: "ok",
      metadata: {},
    },
    {
      id: "tr_asr",
      projectId: PROJECT,
      name: "voice · ASR Viettel rồi NLU",
      sessionId: "zalo_oa:user_551002",
      userId: "user_551002",
      channel: "zalo_oa",
      routeId: "rt_voice",
      release: "oa-prod",
      environment: "production",
      tags: ["asr"],
      startTime: "2026-09-09T11:19:40.000Z",
      endTime: "2026-09-09T11:19:58.000Z",
      status: "ok",
      metadata: {},
    },
  ];

  const observations: Observation[] = [
    obs({
      id: "obs_in_1",
      traceId: "tr_zalo_huy_don",
      type: "channel.inbound",
      name: "zalo.inbound",
      startTime: at("2026-09-09T14:02:01.000Z"),
      endTime: at("2026-09-09T14:02:01.120Z"),
      input: { event: "user_send_text", text: "hủy đơn" },
      output: { msg_id: "m_1001", user_id: "user_847712" },
      metadata: { channel: "zalo_oa" },
    }),
    obs({
      id: "obs_nlu_1",
      traceId: "tr_zalo_huy_don",
      parentId: "obs_in_1",
      type: "nlu",
      name: "fpt.nlu",
      startTime: at("2026-09-09T14:02:01.200Z"),
      endTime: at("2026-09-09T14:02:01.540Z"),
      input: { text: "hủy đơn" },
      output: { intent: "cancel_order", confidence: 0.93 },
      metadata: { route: "fpt-conversation" },
    }),
    obs({
      id: "obs_gen_1",
      traceId: "tr_zalo_huy_don",
      parentId: "obs_nlu_1",
      type: "generation",
      name: "anthropic.messages.create",
      startTime: at("2026-09-09T14:02:01.600Z"),
      endTime: at("2026-09-09T14:02:03.100Z"),
      model: "claude-sonnet-4-5",
      provider: "anthropic",
      input: { messages: [{ role: "user", content: "Khách: hủy đơn. Intent=cancel_order. Hỏi mã đơn." }] },
      output: { text: "Dạ, anh/chị cho em xin mã đơn để hủy ạ?" },
      usage: { inputTokens: 412, outputTokens: 38, estimatedCostUsd: 0.0018 },
    }),
    obs({
      id: "obs_out_1",
      traceId: "tr_zalo_huy_don",
      parentId: "obs_gen_1",
      type: "channel.outbound",
      name: "zalo.outbound",
      startTime: at("2026-09-09T14:03:07.800Z"),
      endTime: at("2026-09-09T14:03:08.000Z"),
      input: { text: "Dạ, anh/chị cho em xin mã đơn để hủy ạ?" },
      output: { event: "oa_send_text", msg_id: "m_1002", quote_msg_id: "m_1001" },
    }),
    obs({
      id: "obs_in_2",
      traceId: "tr_zalo_chao",
      type: "channel.inbound",
      name: "zalo.inbound",
      startTime: at("2026-09-09T09:11:00.000Z"),
      endTime: at("2026-09-09T09:11:00.080Z"),
      input: { event: "follow" },
      output: { user_id: "user_229001" },
    }),
    obs({
      id: "obs_out_2",
      traceId: "tr_zalo_chao",
      parentId: "obs_in_2",
      type: "channel.outbound",
      name: "zalo.outbound",
      startTime: at("2026-09-09T09:11:21.000Z"),
      endTime: at("2026-09-09T09:11:22.000Z"),
      input: { text: "Chào anh/chị, em là trợ lý OA. Anh/chị cần hỗ trợ gì ạ?" },
      output: { event: "oa_send_text", msg_id: "m_2001" },
    }),
    obs({
      id: "obs_in_3",
      traceId: "tr_crm_tool",
      type: "channel.inbound",
      name: "zalo.inbound",
      startTime: at("2026-09-09T14:04:00.000Z"),
      endTime: at("2026-09-09T14:04:00.050Z"),
      input: { event: "user_send_text", text: "DH-88421" },
      output: { msg_id: "m_1003" },
    }),
    obs({
      id: "obs_tool_3",
      traceId: "tr_crm_tool",
      parentId: "obs_in_3",
      type: "tool",
      name: "crm.lookup_order",
      startTime: at("2026-09-09T14:04:00.200Z"),
      endTime: at("2026-09-09T14:04:00.410Z"),
      input: { order_id: "DH-88421" },
      output: { status: "paid", cancellable: true },
    }),
    obs({
      id: "obs_gen_3",
      traceId: "tr_crm_tool",
      parentId: "obs_tool_3",
      type: "generation",
      name: "anthropic.messages.create",
      startTime: at("2026-09-09T14:04:00.500Z"),
      endTime: at("2026-09-09T14:04:02.000Z"),
      model: "claude-sonnet-4-5",
      provider: "anthropic",
      input: { order: "DH-88421" },
      output: { text: "Em đã ghi nhận hủy DH-88421. Hoàn tiền trong 1–3 ngày làm việc." },
      usage: { inputTokens: 880, outputTokens: 52, estimatedCostUsd: 0.0031 },
    }),
    obs({
      id: "obs_out_3",
      traceId: "tr_crm_tool",
      parentId: "obs_gen_3",
      type: "channel.outbound",
      name: "zalo.outbound",
      startTime: at("2026-09-09T14:04:40.700Z"),
      endTime: at("2026-09-09T14:04:41.000Z"),
      input: { text: "Em đã ghi nhận hủy DH-88421. Hoàn tiền trong 1–3 ngày làm việc." },
      output: { msg_id: "m_1004" },
    }),
    obs({
      id: "obs_asr",
      traceId: "tr_asr",
      type: "speech.asr",
      name: "viettel.asr",
      startTime: at("2026-09-09T11:19:40.000Z"),
      endTime: at("2026-09-09T11:19:46.000Z"),
      input: { format: "wav", duration_hint_ms: 2400 },
      output: { text: "cho mình hỏi giờ mở cửa" },
      usage: { audioMs: 2400 },
      metadata: { retained_audio: false },
    }),
    obs({
      id: "obs_nlu_asr",
      traceId: "tr_asr",
      parentId: "obs_asr",
      type: "nlu",
      name: "viettel.nlp",
      startTime: at("2026-09-09T11:19:46.100Z"),
      endTime: at("2026-09-09T11:19:46.400Z"),
      input: { text: "cho mình hỏi giờ mở cửa" },
      output: { intent: "hours", entities: [] },
    }),
    obs({
      id: "obs_tts",
      traceId: "tr_viettel_tts",
      type: "speech.tts",
      name: "viettel.tts",
      startTime: at("2026-09-09T11:20:10.000Z"),
      endTime: at("2026-09-09T11:20:17.400Z"),
      input: { text: "Cửa hàng mở cửa từ 8 giờ đến 21 giờ ạ.", voice: "hn-quynhanh", speed: 1 },
      output: { format: "mp3", duration_ms: 3100 },
      usage: { audioMs: 3100, voiceId: "hn-quynhanh" },
    }),
    obs({
      id: "obs_out_tts",
      traceId: "tr_viettel_tts",
      parentId: "obs_tts",
      type: "channel.outbound",
      name: "zalo.outbound",
      startTime: at("2026-09-09T11:20:17.500Z"),
      endTime: at("2026-09-09T11:20:18.000Z"),
      input: { voice_note: true },
      output: { msg_id: "m_voice_9" },
    }),
    obs({
      id: "obs_err",
      traceId: "tr_anthropic_err",
      type: "generation",
      name: "anthropic.messages.create",
      startTime: at("2026-09-08T18:44:00.000Z"),
      endTime: at("2026-09-08T18:44:02.000Z"),
      status: "error",
      model: "claude-sonnet-4-5",
      provider: "anthropic",
      input: { messages: [{ role: "user", content: "..." }] },
      output: { error: "rate_limit_error" },
    }),
    obs({
      id: "obs_lark_in",
      traceId: "tr_lark_dm",
      type: "channel.inbound",
      name: "lark.inbound",
      startTime: at("2026-09-09T08:02:10.000Z"),
      endTime: at("2026-09-09T08:02:10.040Z"),
      input: { event: "im.message.receive_v1", text: "stand-up lúc mấy?" },
      output: { message_id: "om_1" },
    }),
    obs({
      id: "obs_lark_gen",
      traceId: "tr_lark_dm",
      parentId: "obs_lark_in",
      type: "generation",
      name: "anthropic.messages.create",
      startTime: at("2026-09-09T08:02:10.100Z"),
      endTime: at("2026-09-09T08:02:11.800Z"),
      model: "claude-sonnet-4-5",
      provider: "anthropic",
      output: { text: "Stand-up 9:15 hàng ngày trên channel #eng." },
      usage: { inputTokens: 120, outputTokens: 22, estimatedCostUsd: 0.0004 },
    }),
    obs({
      id: "obs_gchat_in",
      traceId: "tr_gchat",
      type: "channel.inbound",
      name: "googlechat.inbound",
      startTime: at("2026-09-09T07:30:00.000Z"),
      endTime: at("2026-09-09T07:30:00.030Z"),
      input: { text: "reset mật khẩu VPN" },
      metadata: { note: "Không dùng credential Vertex" },
    }),
    obs({
      id: "obs_play",
      traceId: "tr_playground",
      type: "generation",
      name: "playground.chat",
      startTime: at("2026-09-09T16:01:00.000Z"),
      endTime: at("2026-09-09T16:01:04.000Z"),
      model: "claude-sonnet-4-5",
      provider: "anthropic",
      input: { messages: [{ role: "user", content: "Viết câu trả lời OA khi khách muốn đổi size." }] },
      output: { text: "Dạ, anh/chị cho em xin mã đơn và size muốn đổi ạ." },
      usage: { inputTokens: 90, outputTokens: 28, estimatedCostUsd: 0.0005 },
    }),
    obs({
      id: "obs_bed",
      traceId: "tr_bedrock",
      type: "generation",
      name: "bedrock.converse",
      startTime: at("2026-09-09T12:10:01.000Z"),
      endTime: at("2026-09-09T12:10:08.200Z"),
      model: "amazon.nova-lite-v1:0",
      provider: "bedrock",
      region: "ap-southeast-1",
      output: { text: "Em kiểm tra kho giúp anh/chị nhé." },
      usage: { inputTokens: 210, outputTokens: 18, estimatedCostUsd: 0.0002 },
    }),
    obs({
      id: "obs_vertex",
      traceId: "tr_vertex",
      type: "generation",
      name: "vertex.generateContent",
      startTime: at("2026-09-09T12:12:00.000Z"),
      endTime: at("2026-09-09T12:12:05.400Z"),
      model: "gemini-2.5-flash",
      provider: "vertex",
      region: "asia-southeast1",
      output: { text: "ok" },
      usage: { inputTokens: 40, outputTokens: 4, estimatedCostUsd: 0.0001 },
      metadata: { safety: [] },
    }),
    obs({
      id: "obs_teams_in",
      traceId: "tr_foundry_teams",
      type: "channel.inbound",
      name: "msteams.inbound",
      startTime: at("2026-09-09T10:00:00.000Z"),
      endTime: at("2026-09-09T10:00:00.020Z"),
      input: { text: "Tóm tắt ticket INC-442" },
    }),
    obs({
      id: "obs_foundry",
      traceId: "tr_foundry_teams",
      parentId: "obs_teams_in",
      type: "generation",
      name: "foundry.chat.completions",
      startTime: at("2026-09-09T10:00:00.100Z"),
      endTime: at("2026-09-09T10:00:12.000Z"),
      model: "gpt-4o-cx",
      provider: "foundry",
      region: "eastasia",
      output: { text: "INC-442: VPN timeout — đang chờ mạng nội bộ." },
      usage: { inputTokens: 640, outputTokens: 41, estimatedCostUsd: 0.0044 },
      metadata: { deployment: "gpt-4o-cx", apiVersion: "2024-10-21" },
    }),
    obs({
      id: "obs_fpt_wh",
      traceId: "tr_fpt_webhook",
      type: "nlu",
      name: "fpt.webhook",
      startTime: at("2026-09-09T13:40:00.000Z"),
      endTime: at("2026-09-09T13:40:00.200Z"),
      input: { sender_id: "user_9102" },
      output: { messages: [{ type: "text", content: "Em chưa hiểu, anh/chị nói lại giúp em?" }] },
      metadata: { intent: "unknown" },
    }),
  ];

  return {
    orgs: [
      {
        id: ORG,
        name: "OA Demo",
        plan: "hobby",
        teamsAddon: false,
        region: "ap-southeast-1",
        createdAt: "2026-08-01T00:00:00.000Z",
      },
    ],
    users: [
      {
        id: "usr_demo",
        email: DEMO_KEYS.email,
        name: "Lan CX",
        passwordHash: hashPassword(DEMO_KEYS.password),
        orgId: ORG,
        sessionEpoch: 0,
      },
    ],
    projects: [
      {
        id: PROJECT,
        orgId: ORG,
        name: "Bot Zalo shop",
        publicKey: DEMO_KEYS.publicKey,
        secretKeyHash: hashSecret(DEMO_KEYS.secretKey),
        webhookSuffix: "hx8k2m",
      },
    ],
    traces,
    observations,
    sessions: [
      { id: "zalo_oa:user_847712", projectId: PROJECT, channel: "zalo_oa", userId: "user_847712", firstSeen: "2026-09-08T18:44:00.000Z", lastSeen: "2026-09-09T14:04:41.000Z" },
      { id: "zalo_oa:user_229001", projectId: PROJECT, channel: "zalo_oa", userId: "user_229001", firstSeen: "2026-09-09T09:11:00.000Z", lastSeen: "2026-09-09T09:11:22.000Z" },
      { id: "zalo_oa:user_551002", projectId: PROJECT, channel: "zalo_oa", userId: "user_551002", firstSeen: "2026-09-09T11:19:40.000Z", lastSeen: "2026-09-09T11:20:18.000Z" },
      { id: "zalo_oa:user_3301", projectId: PROJECT, channel: "zalo_oa", userId: "user_3301", firstSeen: "2026-09-09T12:10:00.000Z", lastSeen: "2026-09-09T12:10:09.000Z" },
      { id: "zalo_oa:user_9102", projectId: PROJECT, channel: "zalo_oa", userId: "user_9102", firstSeen: "2026-09-09T13:40:00.000Z", lastSeen: "2026-09-09T13:40:08.000Z" },
      { id: "lark:ou_88aa", projectId: PROJECT, channel: "lark", userId: "ou_88aa", firstSeen: "2026-09-09T08:02:10.000Z", lastSeen: "2026-09-09T08:02:40.000Z" },
      { id: "gchat:spaces_abc:users_1", projectId: PROJECT, channel: "gchat", userId: "users/113", firstSeen: "2026-09-09T07:30:00.000Z", lastSeen: "2026-09-09T07:30:19.000Z" },
      { id: "msteams:29:conv", projectId: PROJECT, channel: "msteams", userId: "29:aad-user", firstSeen: "2026-09-09T10:00:00.000Z", lastSeen: "2026-09-09T10:00:14.000Z" },
    ],
    scores: [
      {
        id: "sc_1",
        projectId: PROJECT,
        traceId: "tr_zalo_huy_don",
        observationId: "obs_out_1",
        name: "bot_replied",
        value: 1,
        comment: "Đã hỏi mã đơn",
        source: "eval",
        createdAt: "2026-09-09T14:03:09.000Z",
      },
    ],
    prompts: [
      {
        id: "prm_cx",
        projectId: PROJECT,
        name: "oa-cx-system",
        version: 3,
        messages: [{ role: "system", content: "Bạn là nhân viên CSKH OA. Tiếng Việt tự nhiên, không dịch máy. Hỏi đúng một thông tin còn thiếu." }],
        config: { temperature: 0.3 },
        createdAt: "2026-09-01T00:00:00.000Z",
      },
    ],
    channels: [
      {
        id: "ch_zalo_oa",
        projectId: PROJECT,
        type: "zalo_oa",
        name: "Zalo OA shop",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: { appId: DEMO_KEYS.zaloAppId, oaSecret: DEMO_KEYS.zaloOaSecret },
        webhookPath: `/hooks/zalo/oa/${PROJECT}`,
        lastEventAt: "2026-09-09T14:04:41.000Z",
        lastError: null,
        signatureFailures: 0,
      },
      {
        id: "ch_zalo_bot",
        projectId: PROJECT,
        type: "zalo_bot",
        name: "Zalo Bot",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: { botToken: DEMO_KEYS.zaloBotToken },
        webhookPath: `/hooks/zalo/bot/${PROJECT}`,
        lastEventAt: null,
        lastError: null,
        signatureFailures: 0,
      },
      {
        id: "ch_fpt",
        projectId: PROJECT,
        type: "fpt",
        name: "FPT.AI Conversation",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: { webhookToken: DEMO_KEYS.fptToken },
        webhookPath: `/hooks/fpt/${PROJECT}`,
        lastEventAt: "2026-09-09T13:40:00.000Z",
        lastError: null,
        signatureFailures: 0,
      },
      {
        id: "ch_viettel",
        projectId: PROJECT,
        type: "viettel",
        name: "Viettel ASR/TTS/NLP",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: {},
        webhookPath: "",
        lastEventAt: "2026-09-09T11:20:18.000Z",
        lastError: null,
        signatureFailures: 0,
      },
      {
        id: "ch_lark",
        projectId: PROJECT,
        type: "lark",
        name: "Lark",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: { verificationToken: DEMO_KEYS.larkToken, webhookToken: DEMO_KEYS.larkToken },
        webhookPath: `/hooks/lark/${PROJECT}`,
        lastEventAt: "2026-09-09T08:02:10.000Z",
        lastError: null,
        signatureFailures: 0,
      },
      {
        id: "ch_gchat",
        projectId: PROJECT,
        type: "gchat",
        name: "Google Chat",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: { verificationToken: DEMO_KEYS.gchatToken, webhookToken: DEMO_KEYS.gchatToken },
        webhookPath: `/hooks/google-chat/${PROJECT}`,
        lastEventAt: "2026-09-09T07:30:00.000Z",
        lastError: null,
        signatureFailures: 0,
      },
      {
        id: "ch_teams",
        projectId: PROJECT,
        type: "msteams",
        name: ".NET / Teams",
        enabled: true,
        forwardUrl: null,
        forwardEnabled: false,
        secrets: {},
        webhookPath: "",
        lastEventAt: "2026-09-09T10:00:00.000Z",
        lastError: null,
        signatureFailures: 0,
      },
    ],
    routes: [
      { id: "rt_zalo_fpt_claude", projectId: PROJECT, name: "zalo-oa → fpt-conversation → claude → zalo-reply", steps: ["zalo.inbound", "fpt.nlu", "generation", "zalo.outbound"] },
      { id: "rt_voice", projectId: PROJECT, name: "zalo-oa → viettel-asr → nlu → tts → zalo-reply", steps: ["zalo.inbound", "speech.asr", "nlu", "speech.tts", "zalo.outbound"] },
      { id: "rt_zalo_bedrock", projectId: PROJECT, name: "zalo-oa → bedrock → zalo-reply", steps: ["zalo.inbound", "generation", "zalo.outbound"] },
      { id: "rt_lark", projectId: PROJECT, name: "lark → claude → lark", steps: ["lark.inbound", "generation", "lark.outbound"] },
      { id: "rt_gchat", projectId: PROJECT, name: "google-chat → generation", steps: ["googlechat.inbound", "generation"] },
      { id: "rt_teams_foundry", projectId: PROJECT, name: "teams → foundry", steps: ["msteams.inbound", "generation"] },
    ],
    webhookReplays: [],
    connections: [
      { id: "llm_ant", projectId: PROJECT, provider: "anthropic", name: "Anthropic", region: null, model: "claude-sonnet-4-5", lastPingMs: 420, lastPingAt: "2026-09-09T16:00:00.000Z", lastPingOk: true },
      { id: "llm_fpt", projectId: PROJECT, provider: "fpt-factory", name: "FPT AI Factory", region: "VN", model: null, lastPingMs: null, lastPingAt: null, lastPingOk: null },
      { id: "llm_bed", projectId: PROJECT, provider: "bedrock", name: "Amazon Bedrock", region: "ap-southeast-1", model: "amazon.nova-lite-v1:0", lastPingMs: 610, lastPingAt: "2026-09-09T12:00:00.000Z", lastPingOk: true },
      { id: "llm_vtx", projectId: PROJECT, provider: "vertex", name: "Google Cloud Vertex AI", region: "asia-southeast1", model: "gemini-2.5-flash", lastPingMs: 540, lastPingAt: "2026-09-09T12:00:00.000Z", lastPingOk: true },
      { id: "llm_fnd", projectId: PROJECT, provider: "foundry", name: "Microsoft Foundry", region: "eastasia", model: "gpt-4o-cx", lastPingMs: 700, lastPingAt: "2026-09-09T10:00:00.000Z", lastPingOk: true },
    ],
  };
}
